const syllabus = [
  {
    subject: "Physics",
    subTopics: [
      {
        name: "Mechanics",
        chapters: [
          {
            chapter_id: 1,
            chapter_name: "Units and Dimensions",
            total_videos: "50",
            total_tests: "3",
            notes: "20 pages",
            topics: [
              "Introduction to units",
              "Dimensional analysis",
              "SI units",
              "Dimensional formulas",
              "Dimensional equations",
            ],
          },
          // Add other chapters under Mechanics here
          {
            chapter_id: 2,
            chapter_name: "Kinematics",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Motion in one dimension",
              "Motion in two dimensions",
              "Uniform and non-uniform motion",
              "Acceleration",
              "Equations of motion",
            ],
          },
          {
            chapter_id: 3,
            chapter_name: "Laws of Motion",
            total_videos: "70",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Newton's laws of motion",
              "Inertia and its types",
              "Force",
              "Friction",
              "Applications of laws of motion",
            ],
          },
          {
            chapter_id: 4,
            chapter_name: "Work, Energy, and Power",
            total_videos: "60",
            total_tests: "3",
            notes: "18 pages",
            topics: [
              "Work",
              "Energy",
              "Power",
              "Conservation of energy",
              "Gravitational potential energy",
            ],
          },
          {
            chapter_id: 5,
            chapter_name: "Rotational Motion",
            total_videos: "90",
            total_tests: "6",
            notes: "30 pages",
            topics: [
              "Rotational kinematics",
              "Torque",
              "Moment of inertia",
              "Angular momentum",
              "Rolling motion",
            ],
          },
          {
            chapter_id: 6,
            chapter_name: "Gravitation",
            total_videos: "65",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Gravitational force",
              "Newton's law of universal gravitation",
              "Gravitational field",
              "Escape velocity",
              "Satellites",
            ],
          },
          {
            chapter_id: 7,
            chapter_name: "Properties of Matter",
            total_videos: "75",
            total_tests: "5",
            notes: "22 pages",
            topics: [
              "Elasticity",
              "Stress and strain",
              "Surface tension",
              "Viscosity",
              "Fluid mechanics",
            ],
          },
        ],
      },
      {
        name: "Waves and Thermodynamics",
        chapters: [
          {
            chapter_id: 8,
            chapter_name: "Thermodynamics",
            total_videos: "85",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Thermal equilibrium",
              "Zeroth law of thermodynamics",
              "First law of thermodynamics",
              "Second law of thermodynamics",
              "Heat engines",
            ],
          },
          {
            chapter_id: 9,
            chapter_name: "Kinetic Theory of Gases",
            total_videos: "55",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Kinetic theory",
              "Gas laws",
              "Mean free path",
              "Specific heat capacity",
              "Thermal conductivity",
            ],
          },
          {
            chapter_id: 10,
            chapter_name: "Oscillations and Waves",
            total_videos: "100",
            total_tests: "6",
            notes: "28 pages",
            topics: [
              "Simple harmonic motion",
              "Damped oscillations",
              "Wave motion",
              "Wave properties",
              "Superposition principle",
            ],
          },
        ],
      },
      {
        name: "Electricity and Magnetism",
        chapters: [
          {
            chapter_id: 11,
            chapter_name: "Electrostatics",
            total_videos: "90",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Coulomb's law",
              "Electric field",
              "Gauss's law",
              "Electric potential",
              "Capacitance",
            ],
          },
          {
            chapter_id: 12,
            chapter_name: "Current Electricity",
            total_videos: "80",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Electric current",
              "Ohm's law",
              "Kirchhoff's laws",
              "Electrical resistance",
              "Electromotive force",
            ],
          },
          {
            chapter_id: 13,
            chapter_name: "Magnetic Effects of Current and Magnetism",
            total_videos: "85",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Magnetic field",
              "Magnetic force",
              "Magnetic flux",
              "Ampere's law",
              "Faraday's law",
            ],
          },
          {
            chapter_id: 14,
            chapter_name: "Electromagnetic Induction and Alternating Currents",
            total_videos: "75",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Electromagnetic induction",
              "Faraday's law",
              "Lenz's law",
              "Alternating current",
              "Transformers",
            ],
          },
          {
            chapter_id: 15,
            chapter_name: "Electromagnetic Waves",
            total_videos: "60",
            total_tests: "3",
            notes: "20 pages",
            topics: [
              "Electromagnetic spectrum",
              "Maxwell's equations",
              "Properties of electromagnetic waves",
              "Applications of electromagnetic waves",
              "Electromagnetic radiation",
            ],
          },
        ],
      },
      {
        name: "Optics and Modern Physics",
        chapters: [
          {
            chapter_id: 16,
            chapter_name: "Ray Optics",
            total_videos: "70",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Reflection",
              "Refraction",
              "Total internal reflection",
              "Lens",
              "Optical instruments",
            ],
          },
          {
            chapter_id: 17,
            chapter_name: "Wave Optics",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Interference",
              "Diffraction",
              "Polarization",
              "Huygen's principle",
              "Young's double slit experiment",
            ],
          },
          {
            chapter_id: 18,
            chapter_name: "Dual Nature of Matter and Radiation",
            total_videos: "65",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Particle nature of light",
              "Wave-particle duality",
              "Photoelectric effect",
              "De Broglie wavelength",
              "Davisson-Germer experiment",
            ],
          },
          {
            chapter_id: 19,
            chapter_name: "Atoms and Nuclei",
            total_videos: "70",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Atomic structure",
              "Bohr model",
              "Radioactivity",
              "Nuclear reactions",
              "Nuclear fission and fusion",
            ],
          },
          {
            chapter_id: 20,
            chapter_name: "Electronic Devices",
            total_videos: "75",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Semiconductors",
              "Diodes",
              "Transistors",
              "Logic gates",
              "Integrated circuits",
            ],
          },
          {
            chapter_id: 21,
            chapter_name: "Communication Systems",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Elements of communication systems",
              "Propagation of electromagnetic waves",
              "Antennas",
              "Modulation",
              "Amplitude modulation",
            ],
          },
        ],
      },
    ],
  },
  {
    subject: "Chemistry",
    subTopics: [
      {
        name: "Physical Chemistry",
        chapters: [
          {
            chapter_id: 1,
            chapter_name: "Basic Concepts of Chemistry",
            total_videos: "50",
            total_tests: "3",
            notes: "20 pages",
            topics: [
              "Laws of chemical combination",
              "Dalton's atomic theory",
              "Atomic and molecular masses",
              "Mole concept",
              "Empirical and molecular formulae",
            ],
          },
          {
            chapter_id: 2,
            chapter_name: "Environmental Chemistry",
            total_videos: "80",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Environmental pollutants",
              "Air pollution",
              "Water pollution",
              "Soil pollution",
              "Green chemistry",
            ],
          },
          {
            chapter_id: 3,
            chapter_name: "States of Matter: Gases and Liquids",
            total_videos: "80",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Gas laws",
              "Kinetic theory of gases",
              "Liquid state",
              "Intermolecular forces",
              "Vapour pressure",
            ],
          },
          {
            chapter_id: 4,
            chapter_name: "Thermodynamics",
            total_videos: "75",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Thermal equilibrium",
              "Zeroth law of thermodynamics",
              "First law of thermodynamics",
              "Second law of thermodynamics",
              "Heat engines",
            ],
          },
          {
            chapter_id: 5,
            chapter_name: "Equilibrium",
            total_videos: "85",
            total_tests: "6",
            notes: "28 pages",
            topics: [
              "Types of equilibrium",
              "Law of chemical equilibrium",
              "Equilibrium constant",
              "Le Chatelier's principle",
              "Factors affecting equilibrium",
            ],
          },
        ],
      },
      {
        name: "Organic Chemistry",
        chapters: [
          {
            chapter_id: 6,
            chapter_name: "Chemical Bonding and Molecular Structure",
            total_videos: "60",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Ionic bond",
              "Covalent bond",
              "Molecular orbital theory",
              "VSEPR theory",
              "Hydrogen bonding",
            ],
          },
          {
            chapter_id: 7,
            chapter_name: "Redox Reactions",
            total_videos: "70",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Oxidation-reduction reactions",
              "Balancing redox reactions",
              "Electrochemical cells",
              "Nernst equation",
              "Corrosion",
            ],
          },
          {
            chapter_id: 8,
            chapter_name:
              "Organic Chemistry - Some Basic Principles and Techniques",
            total_videos: "65",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Hybridization",
              "Isomerism",
              "Types of organic reactions",
              "Purification of organic compounds",
              "Qualitative analysis",
            ],
          },
          {
            chapter_id: 9,
            chapter_name: "Hydrocarbons",
            total_videos: "70",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Classification of hydrocarbons",
              "Alkanes",
              "Alkenes",
              "Alkynes",
              "Aromatic hydrocarbons",
            ],
          },
        ],
      },
      {
        name: "InOrganic Chemistry",
        chapters: [
          {
            chapter_id: 10,
            chapter_name: "Structure of Atom",
            total_videos: "60",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Discovery of electron, proton, and neutron",
              "Atomic models",
              "Bohr's model",
              "Dual nature of matter and radiation",
              "Quantum numbers",
            ],
          },
          {
            chapter_id: 11,
            chapter_name:
              "Classification of Elements and Periodicity in Properties",
            total_videos: "70",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Modern periodic law",
              "Types of elements",
              "Periodic trends",
              "Electronic configuration",
              "Periodic properties",
            ],
          },
          {
            chapter_id: 12,
            chapter_name: "Hydrogen",
            total_videos: "65",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Position of hydrogen in periodic table",
              "Isotopes of hydrogen",
              "Hydrides",
              "Water",
              "Hydrogen peroxide",
            ],
          },
          {
            chapter_id: 13,
            chapter_name: "s-Block Elements",
            total_videos: "75",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Group 1 elements",
              "Group 2 elements",
              "Properties and reactions",
              "Anomalous properties",
              "Uses of alkali and alkaline earth metals",
            ],
          },
          {
            chapter_id: 14,
            chapter_name: "p-Block Elements",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Group 13-18 elements",
              "Electronic configuration",
              "Trends in properties",
              "Reactions of p-block elements",
              "Uses of p-block elements",
            ],
          },
        ],
      },
    ],
  },
  {
    subject: "Maths",
    subTopics: [
      {
        name: "Sets Relations and Functions",
        chapters: [
          {
            chapter_id: 1,
            chapter_name: "Sets, Relations, and Functions",
            total_videos: "80",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Sets and their representations",
              "Union, intersection, and complement of sets",
              "Relations and functions",
              "Types of relations",
              "Types of functions",
            ],
          },
          {
            chapter_id: 2,
            chapter_name: "Trigonometry",
            total_videos: "75",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Trigonometric ratios",
              "Trigonometric identities",
              "Trigonometric equations",
              "Properties of triangles",
              "Height and distance",
            ],
          },
        ],
      },
      {
        name: "Algebra",
        chapters: [
          {
            chapter_id: 3,
            chapter_name: "Complex Numbers and Quadratic Equations",
            total_videos: "90",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Complex numbers",
              "Algebra of complex numbers",
              "Quadratic equations",
              "Roots of quadratic equations",
              "Nature of roots",
            ],
          },
          {
            chapter_id: 4,
            chapter_name: "Matrices and Determinants",
            total_videos: "75",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Matrices",
              "Types of matrices",
              "Operations on matrices",
              "Determinants",
              "Properties of determinants",
            ],
          },
          {
            chapter_id: 5,
            chapter_name: "Permutations and Combinations",
            total_videos: "85",
            total_tests: "6",
            notes: "28 pages",
            topics: [
              "Fundamental principle of counting",
              "Permutations",
              "Combinations",
              "Binomial theorem",
              "Applications of permutations and combinations",
            ],
          },
          {
            chapter_id: 6,
            chapter_name: "Mathematical Induction",
            total_videos: "70",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Principle of mathematical induction",
              "Inductive step",
              "Applications of mathematical induction",
              "Strong induction",
              "Recursive definitions and formulas",
            ],
          },
          {
            chapter_id: 7,
            chapter_name: "Binomial Theorem and its Simple Applications",
            total_videos: "65",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Binomial theorem for positive integral indices",
              "Binomial theorem for any index",
              "Binomial coefficients",
              "Applications of binomial theorem",
            ],
          },
          {
            chapter_id: 8,
            chapter_name: "Sequences and Series",
            total_videos: "75",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Arithmetic progression",
              "Geometric progression",
              "Sum of n terms",
              "Special series",
              "Infinite series",
            ],
          },
        ],
      },
      {
        name: "Co-ordinate Geometry",
        chapters: [
          {
            chapter_id: 9,
            chapter_name: "Coordinate Geometry",
            total_videos: "80",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Straight lines",
              "Circles",
              "Conic sections",
              "Parabola",
              "Ellipse and hyperbola",
            ],
          },
        ],
      },
      {
        name: "Calculus",
        chapters: [
          {
            chapter_id: 10,
            chapter_name: "Limits, Continuity, and Differentiability",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Limits",
              "Continuity",
              "Differentiability",
              "Derivatives",
              "Rolle's theorem and mean value theorem",
            ],
          },
          {
            chapter_id: 11,
            chapter_name: "Integral Calculus",
            total_videos: "65",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Indefinite integrals",
              "Definite integrals",
              "Integration by parts",
              "Integration by substitution",
              "Properties of integrals",
            ],
          },
          {
            chapter_id: 12,
            chapter_name: "Differential Equations",
            total_videos: "70",
            total_tests: "4",
            notes: "20 pages",
            topics: [
              "Ordinary differential equations",
              "Formation of differential equations",
              "Solutions of differential equations",
              "Variables separable method",
              "Homogeneous differential equations",
            ],
          },
        ],
      },
      {
        name: "Statistics and Probability",
        chapters: [
          {
            chapter_id: 13,
            chapter_name: "Statistics and Probability",
            total_videos: "70",
            total_tests: "4",
            notes: "22 pages",
            topics: [
              "Measures of central tendency",
              "Measures of dispersion",
              "Probability",
              "Random variables",
              "Binomial distribution",
            ],
          },
        ],
      },
      {
        name: "Vector and 3-Dimensional Geometry",
        chapters: [
          {
            chapter_id: 14,
            chapter_name: "Three Dimensional Geometry",
            total_videos: "75",
            total_tests: "5",
            notes: "24 pages",
            topics: [
              "Coordinates in space",
              "Distance between two points",
              "Section formula",
              "Direction cosines and direction ratios",
              "Equation of a straight line in space",
            ],
          },
          {
            chapter_id: 15,
            chapter_name: "Vector Algebra",
            total_videos: "80",
            total_tests: "5",
            notes: "25 pages",
            topics: [
              "Vector addition",
              "Scalar multiplication",
              "Dot and cross products",
              "Scalar and vector triple products",
              "Applications of vectors",
            ],
          },
        ],
      },
    ],
  },
];

export const topicHandler = (subjectName) => {
  const subject = syllabus.find((subject) => subject.subject === subjectName);
  if (subject) {
    return subject.subTopics.flatMap((topic) =>
      topic.chapters.map((chapter) => ({
        label: chapter.chapter_name,
        value: chapter.chapter_id,
      }))
    );
  }
  return [];
};

export const getChapterData = (subjectName, subTopicName, chapterName) => {
  const subject = syllabus.find((subject) => subject.subject === subjectName);
  if (subject) {
    const subTopics = subject.subTopics;
    let chapterData = [];

    subTopics.forEach((topic) => {
      if (!subTopicName || topic.name === subTopicName) {
        topic.chapters.forEach((chapter) => {
          if (!chapterName || chapter.chapter_name === chapterName) {
            chapterData.push(chapter);
          }
        });
      }
    });

    return chapterData;
  } else {
    return [];
  }
};

var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

var comments = [
  "Hello, how are you?",
  "I'm doing great, thanks for asking!",
  "Hey there, what's up?",
  "Not much, just relaxing at home.",
  "What's on your mind today?",
  "I'm feeling a bit tired, but I'll survive.",
  "How's your day been so far?",
  "It's been a busy day, but I'm managing.",
  "What's new in your world?",
  "Just the usual routine, nothing exciting.",
  "I can relate to that, sometimes life gets monotonous.",
  "Got any plans for the weekend?",
  "I'm thinking about going for a hike. You?",
  "I might catch up on some reading. Enjoy your hike!",
  "Thanks! Reading sounds nice and relaxing.",
  "Do you have any book recommendations?",
  "Have you read 'The Great Gatsby'?",
  "Yes, I loved it! It's a classic for a reason.",
  "Absolutely, Fitzgerald's writing is mesmerizing.",
  "What's your favorite genre of music?",
  "I'm into rock and indie. How about you?",
  "I'm a jazz and blues fan, love the classics.",
  "Any good jazz albums you'd recommend?",
  "Check out Miles Davis' 'Kind of Blue' for a start.",
  "Thanks, I'll give it a listen!",
  "You're welcome! Enjoy the music.",
  "How's your family doing?",
  "They're doing well, thanks for asking. Yours?",
  "Everyone's good, just a bit scattered these days.",
  "Family is everything, right?",
  "Indeed, they're our support system.",
  "Well, it was nice chatting with you!",
  "Likewise! Have a great day!",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function makeRandomMessage(length) {
  return comments[Math.floor(Math.random() * comments.length)];
}
